### PR TITLE
Grab latest k8s binaries automatically

### PR DESCRIPTION
**Pull request by rimusz**
It will automatically download latest kubernetes binaries on each boot

### CODE REVIEW

**Comment by pires** [comment]
This is very interesting but I push upgrades only after validating the releases are working. Running bleeding-edge may break the purpose of this repository.

Given this, I suggest to copy current ```master.yaml```and ```node.yaml``` to a new folder (named ```latest```), change accordingly and add instructions on ```README.md``` for the ones wanting to try-out the bleeding-edge. How does that sound to you?

**Comment by rimusz** [comment]
@pires it is up to mate. I just using the same approach for my other project, which works very well,
as https://get.k8s.io is an official kubernetes install script from google, which gets updated only when their release the latest k8s version. :)

**Comment by pires** [comment]
@rimusz I'm aware of that, but some releases are buggy - remember 0.8.0 that broke services? ;-)

Anyway, I'll rebase this on my branch, change things and merge. Thanks for contributing.

**Comment by rimusz** [comment]
@pires no worries, this one is only the vagrant one for testing k8s. 
For production I'm for sure going to use tested versions only.

**Comment by rimusz** [comment]
@pires btw, for easier switching between versions I think it is better to move k8s services to fleet units with some extra script to switch the version in fleet units and then destroy and start fleet units again.
One CoreOS install then can handle both :-)

**Pull request merged**
