### PR TITLE
Updated setup to 0.14.2

### PR DESCRIPTION
**Pull request by w0mbat**

### CODE REVIEW

**Comment by pires** [comment]
@w0mbat thank you, but had it already pending. https://github.com/pires/kubernetes-vagrant-coreos-cluster/commit/f4daad950ca804630b803e4a63c49b2c930fee82

**Comment by w0mbat** [comment]
yeah, but the setup.sh file didn´t install the current tools for 0.14.2, because it references a seperate version (0.13.2).

**Comment by pires** [comment]
@w0mbat thank you for clarifying on that. My bad ;-)

**Comment by w0mbat** [comment]
haha no worries :)
Will try it also on 0.15.0 with our app within the next hour

**Comment by AntonioMeireles** [comment]
@w0mbat 0.15.0 won't work. @pires and i are working on it :smile:

**Comment by w0mbat** [comment]
@AntonioMeireles @pires Great! Excited to try it :)

**Pull request merged**
