### PR TITLE
Activated v1beta3 api

### PR DESCRIPTION
**Pull request by w0mbat**

### CODE REVIEW

**Comment by pires** [comment]
Can you please explain this?

**Comment by w0mbat** [comment]
By default the v1beta3 api is not activated and has to be activated with this flag.
This is the Kubernetes ticket that explains it: https://github.com/GoogleCloudPlatform/kubernetes/pull/2878

**Comment by w0mbat** [comment]
By adding the flag, I was still able to add v1beta1 and v1beta2 rcs and services.

**Comment by pires** [comment]
Thank you :-)

**Comment by w0mbat** [comment]
+1

**Pull request merged**
