### PR TITLE
Feature/windows support

### PR DESCRIPTION
**Pull request by Hikariii**
This code supports windows when vagrant is run from a linux-like environment like mingw, cygwin etx.
It needs linux, because sed, rm, mv and other linux like commands are used.

One MAJOR change is that it installs and runs kubectl from the coreos master node.
This is the same as the basic coreos vagrant file, so windows users should be used to it.

The order of the code is somewhat changed because of windows support.
If you want I will explain some of the changes later on when I have more time...

### CODE REVIEW

**Comment by pires** [comment]
@Hikariii great job! Am travelling in a few hours and want to deep test this - and have at least one Windows user validating this.

But I have a request, could you update the documentation accordingly and have it committed in this PR, please?

Thank you so much for contributing.

**Comment by pires** [comment]
@analytik @jdojff care to test these changes and provide feedback?

**Comment by Hikariii** [comment]
@pires I'll start with adding some documentation. Looking forward to the testing results.

**Comment by analytik** [comment]
Hi. Thanks for implementing this! I've tested the default setup, and also NFS mapping, things work as expected. ```kubectl``` can connect to the master and work with pods/rc/services.

One thing that didn't work as expected, which is probably just my misunderstanding how Kubernetes works, is that when I run
```bash
kubectl run-container nginx --image=nginx --port=80 --replicas=2
kubectl expose rc nginx --port=80 --api-version="v1beta3" --overrides='{"publicIPs": ["172.17.8.101", "172.17.8.102", "172.17.8.103", "127.0.0.1"], "apiVersion": "v1beta3"}'
```
then I get something like
```
core@master ~ $ kubectl get pods
POD              IP            CONTAINER(S)   IMAGE(S)                                         HOST            LABELS                                                              STATUS    CREATED     MESSAGE
kube-dns-tg7qg   10.244.15.2                                                                   172.17.8.102/   k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   Running   2 hours
                               etcd           quay.io/coreos/etcd:v2.0.3                                                                                                           Running   9 minutes   last termination: exit code 0
                               kube2sky       gcr.io/google_containers/kube2sky:1.2                                                                                                Running   9 minutes   last termination: exit code 2
                               skydns         gcr.io/google_containers/skydns:2015-03-11-001                                                                                       Running   9 minutes   last termination: exit code 2
nginx-omzt6      10.244.21.2                                                                   172.17.8.103/   run-container=nginx                                                 Running   8 minutes
                               nginx          nginx                                                                                                                                Running   8 minutes
nginx-p2glh      10.244.15.3                                                                   172.17.8.102/   run-container=nginx                                                 Running   2 hours
                               nginx          nginx                                                                                                                                Running   9 minutes   last termination: exit code 0
```
and
```
core@master ~ $ kubectl get services
NAME            LABELS                                                              SELECTOR              IP               PORT(S)
kube-dns        k8s-app=kube-dns,kubernetes.io/cluster-service=true,name=kube-dns   k8s-app=kube-dns      10.100.0.10      53/UDP
kubernetes      component=apiserver,provider=kubernetes                             <none>                10.100.0.2       443/TCP
kubernetes-ro   component=apiserver,provider=kubernetes                             <none>                10.100.0.1       80/TCP
nginx           <none>                                                              run-container=nginx   10.100.157.225   80/TCP
```

From master, I can curl the two pods by their ```10.244.*.*``` addresses, but I cannot access ```10.100.157.225```, which should be the IP address of the nginx service, right? I cannot curl ```172.17.8.*``` either. From Windows, I can ping ```172.17.8.*```, but curl doesn't connect.

Sorry if I'm missing something obvious, again, I'm new to this, I just wanted to mention it, since for the [one-node setup](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md) those steps were enough to be able to access the service from the outside.

**Comment by pires** [comment]
@analytik for accessing services from outside of the cluster, namely your host, you need to either set your service `publicIPs` attribute to point to any of the assigned `172.17.8.0/24` addresses (which should point to nodes running `kube-proxy`) and use said IP or you need to do your own routing.

@Hikariii do you have anything to add to this? I will be merging this tomorrow if no more changes are needed.

**Comment by analytik** [comment]
@pires thanks, that's what I thought I'm already doing - when using ```kubectl expose```, I'm specifying ```--overrides='{"publicIPs": ...```. 

My mistake was that when I used API ```v1beta3```, it did not work. I just now tried to specify ```v1beta2``` and now it works, both from master, and from Windows.

Thanks again to both of you!

**Comment by Hikariii** [comment]
I'v tested this with different windows setups (colleagues) and everything seems to work great here. I've got nothing to add for now.

**Comment by pires** [comment]
@Hikariii can you please do a `git squash` and pull again? I don't want commit log garbage in the history...

```
Merge branch 'master' of github.com:pires/kubernetes-vagrant-coreos-cluster into feature/windowsSupport
```

**Comment by pires** [comment]
@Hikariii just waiting for the squash and I'll merge it.

**Comment by pires** [comment]
Nevermind, I'll just merge and squash it. Thank you so much @Hikariii. What a great addition.

**Comment by Hikariii** [comment]
@pires will do next time

**Comment by dbubs** [comment]
The change in setup.tmpl breaks the darwin/linux implementation. "~" does not expand on the shell when quoted. This results in a `./temp/setup: line 44: ~/.bash_profile: No such file or directory` error. This should be changed to `homeDir=~` or `homeDir=$HOME`. Personally, I feel that `$homeDir` is redundant. Why not just use `$HOME` instead? I can submit a PR if you guys agree...

**Comment by pires** [comment]
@dbubs care to make a PR with a fix?

**Comment by dbubs** [comment]
submitted PR #83

**Pull request merged**
