### PR TITLE
Fix for RBAC Support

### PR DESCRIPTION
**Pull request by yudaykiran**
Fix for Issue #262
 
Details of the fix:
--------------------
- Add RBAC authentication in api-server arguments.
- Provide system:masters permission for kube-admin.
- Make kube-dns RBAC compatible.

Signed-off-by: Uday Kiran <udaykiran.y@gmail.com>

### CODE REVIEW

**Comment by yudaykiran** [comment]
How about an environment variable for Vagrant called AUTHORIZATION_MODE? The default mode will create the cluster without RBAC. Someone who really needs RBAC can enable it with the environment variable.

My thoughts on the implementation would be to have separate files for RBAC implementations:
- master-apiserver-rbac.yaml
- dns-service-rbac.yaml
- dns-deployment-rbac.yaml.tmpl
- make-certs-master-rbac.sh

Implement conditionals in Vagrantfile for RBAC mode and update documentation for the same. 

We can use some sed operations and update the files, but I would rather prefer to keep it simple. Even though the differences in the files are minimal, segregating them at an early stage would reduce development effort later.

**Comment by pires** [comment]
Totally agree. Could you take on that next? Would truly appreciate it.

**Comment by yudaykiran** [comment]
Have added a new commit for the same pull request, maybe you can review it and let me know your comments.

**Comment by yudaykiran** [comment]
@pires I have integrated the review comments, but I see the kube-controller-manager restarting once, maybe you can help me in the right direction to identify what's causing it. I feel it may be something related to etcd.

**Comment by pires** [comment]
@yudaykiran I need some time to test this. By default, things work. Need to try with RBAC enabled. Will try and do it over the weekend.

**Comment by pires** [comment]
Seems to be working, no restart here.

**Comment by pires** [comment]
Thanks a lot @yudaykiran!!!

**Pull request merged**
