### PR TITLE
replacing curl for ruby Net::HTTP

### PR DESCRIPTION
**Pull request by Hikariii**
Updated commit user :)

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
@Hikariii a) good work!
               b) (curious): any special reason for the code difference between the handling of :8080 vs :10250 ?

**Comment by Hikariii** [comment]
@AntonioMeireles :10250 does not return a valid http response.
This code replaces ```curl -sIf``` that does not need a valid http response to return true just a good connection.
Net::HTTP throws the ```Net::HTTPBadResponse``` exception when a socket can be opened, but the response cannot be parsed to a vallid HTTP response.

see also: https://github.com/ruby/ruby/blob/ca6b174078fa15f33655be704d9409fdbc4f9929/lib/net/http/response.rb#L38-L42
https://github.com/ruby/ruby/blob/ca6b174078fa15f33655be704d9409fdbc4f9929/lib/net/http/response.rb#L60-L62

**Comment by Hikariii** [comment]
If there is a different url to check if a node is up which gives a valid http response then it would be better to use that I guess.
I just used the url that was already there.

**Comment by AntonioMeireles** [comment]
@Hikariii ok, got it. thanks!!!!!!

**Pull request merged**
