### PR TITLE
à la carte synced folders, etcd and k8s' version bumps plus some doc tweaks.

### PR DESCRIPTION
**Pull request by AntonioMeireles**

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
@albertocsm @pires *before* mergings (lacks docs) can you guys give this a try? :eyes:

(fwiw it's very lightly tested - just spent 5m on it)

**Comment by albertocsm** [comment]
@AntonioMeireles looks good. will try it asap

**Comment by pires** [comment]
Tried and works great! Tell me when you feel it's ready for merging.

**Comment by AntonioMeireles** [comment]
OK. Good to hear. Will add reference to this on docs tomorrow morning.
:smile:

--
sent from my mobile

**Comment by pires** [comment]
@AntonioMeireles why can't we just agree on a PR per issue? It's becoming harder and harder to review some of your PRs. I'm merging this, but next time, I'll become a PITA ;-)

**Pull request merged**
