### PR TITLE
Support of new docker registry 2.x

### PR DESCRIPTION
**Pull request by remoe**
This is my first try to use docker registry 2.x as a docker-cache. Please review. Thanks.

### CODE REVIEW

**Comment by pires** [comment]
@remoe how did you test if this is working aka caching images?

**Comment by remoe** [comment]
@pires, it's not finished. This is documented here:

https://blog.docker.com/2015/10/registry-proxy-cache-docker-open-source/
"Test your registry proxy cache"

I have some issues with it:

- It should be possible to query the v2 API. But it throws 405 on some queries:

```bash
master core # curl -I -k https://127.0.0.1:5000/v2/_catalog
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: text/plain; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Date: Sun, 22 Nov 2015 11:04:31 GMT
Content-Length: 19

master core # curl -I -k https://127.0.0.1:5000/v2/
HTTP/1.1 200 OK
Content-Length: 2
Content-Type: application/json; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Date: Sun, 22 Nov 2015 11:05:08 GMT

master core # curl -I -k https://127.0.0.1:5000/v2/library/busybox/tags/list
HTTP/1.1 405 Method Not Allowed
Allow: GET
Content-Type: text/plain; charset=utf-8
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Date: Sun, 22 Nov 2015 11:05:35 GMT
Content-Length: 19
```

- But when one add a volume to it with ```-v /registry:/var/lib/registry``` then you find the cached files in /registry.

So it needs some additional work.

**Comment by pires** [comment]
@remoe let me know when you feel it's ready for review. I am afraid I won't be able to help much in the coming days/weeks.

**Comment by pires** [comment]
@remoe I tried for a few minutes and I believe you need:
* `-v /docker-cache:/var/lib/registry`
* Generate valid SSL certificates for `master` node IP (`172.17.8.101`) and provision them both to `registry` container and on minions to accept HTTPS.

Without _valid_ SSL certificates, I don't think `docker pull`, on any `node` will fail and proceed to download directly.

**Comment by remoe** [comment]
@peres, what you mean with *valid* SSL certs? Not self generated? I use one of your self generated.

**Comment by pires** [comment]
@remoe how are you using that on each node Docker config? Even when curl'ing you're doing it insecurely with `-k`.

**Comment by remoe** [comment]
@pires, thanks. I haven't the time to testing this, sorry:

```
docker[872]: 2015/11/23 12:56:06 http: TLS handshake error from 172.18.8.2:35250: tls: first record does not look like a TLS handshake
docker[872]: 2015/11/23 12:56:07 http: TLS handshake error from 172.18.8.2:35268: remote error: bad certificate
```

**Comment by remoe** [comment]
It it correct to apply a working certificate when one add:

IP:__MASTER_IP__

on this line:

https://github.com/pires/kubernetes-vagrant-coreos-cluster/blob/master/master.yaml#L125

?

**Comment by pires** [comment]
`__MASTER_IP__` is the same as `$public_ipv4`.

**Comment by remoe** [comment]
I think its better to remove make_certs.sh and create all certificates on vagrant-client side with:
https://github.com/cloudflare/cfssl

And then copy this files to master and minions. 

?

**Comment by pires** [comment]
@remoe care to try it on a different PR?

**Comment by pires** [comment]
@remoe you're no longer pursuing this?

**Comment by remoe** [comment]
@pires, sorry currently not, I haven't find the time :/ The task should be easy, but it need some changes in the vagrant file to make it right.

**Pull request closed without merging**
