### PR TITLE
simplifying 'userland' instalation

### PR DESCRIPTION
**Pull request by AntonioMeireles**

### CODE REVIEW

**Comment by pires** [comment]
LGTM. I'm just worried it's getting _too smart_. TBH, I always wanted it to be easy but not _that easy_, since my experience tells me it will attract many users that just want it to work and will not even care about understanding what this smart script does or what ```kubectl``` is and how to get it.

**Comment by pires** [comment]
Leave a comment when you feel the PR is ready to merge.

**Comment by AntonioMeireles** [comment]
by parts...
regarding the (too much) easiness: IMHO the end goal would be to get the audience to focus, spend time, on the real issue - in this case kubernetes and all the mental changes that this '3.0' age technologies bring and not to get _lost_ on the 'little' details of getting to there by _just_ having to setup a simple playground. 

regarding the "merginess" status, feature wise i think it is ok. frankly my only 'doubt' right now is if there could be a saner name to the kubLocalSetup helper script.  

All the best

**Comment by AntonioMeireles** [comment]
actually. hang on 5m.

**Comment by AntonioMeireles** [comment]
ok. latest iteration gets the README a bit more clear about what is going on via the helper script.

**Comment by pires** [comment]
I understand your argument and agree with it. By it doesn't invalidate my concern. I already maintain CoreOS documentation on the official project and most of the time people just don't get the time to read what they're doing.

Merging this and thanks once more for the amazing contribution!

**Pull request merged**
