### PR TITLE
Avoid download binaries on subsequent vagrant up

### LINKED ISSUE #186: Creating Binaries again during vagrant up
Hi, 
When you re-run vagrant up (after a vagrant halt), it re-runs the systemd units thus creating multiple copies of kube-proxy, kubelet, kube-scheduler, kube-apiserver (depending on master/node). Should we be using the ConditionPathExists (or something similar) so that it doesnt re-create the entries.

Same with the kubectl binary. The setup script checks for the directory existence and execute bit conditionally and creates it only if its not there, but the binary is downloaded everytime I run vagrant up. Can we make this conditional or is there a reason behind running it every time. (EDIT: Just saw #154 was raised for this)

I can work on a PR if its acceptable. 

Thanks for building this!

### PR DESCRIPTION
**Pull request by rajasaur**
Instead of downloading the binaries everytime vagrant up is done, do
a ConditionalPath to check for binaries.

This fixes #186

### CODE REVIEW

**Comment by rajasaur** [comment]
Ill do the kubectl version --client and compare it if there is an existing kubectl separately.. The format of it isnt standard (Not sure making it scriptable was a goal during the time it was created), so I want to make sure there arent any future changes to kubectl version that will make the parsing different.

i.e. kubectl version --client returns this:
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}

Probably have to do a sed or a perl regex to extract the GitVersion (Given that there are RCs , Im not sure even if doing it on GitVersion is correct). Ill spend some time on it and provide it as another patch.

**Comment by pires** [comment]
What happens to the unit if somehow one of the binaries is not present but the other one is? It seems it is not run, right?

**Comment by rajasaur** [comment]
By default, they are OR-ed. If any of them is not present (I have a negated flag on the ConditionalPathExists), it will run the whole unit, which will download all of the binaries again.

**Comment by pires** [comment]
:+1: thank you.

**Pull request merged**
