### PR TITLE
Upgraded to Kubernetes 0.21.0.

### PR DESCRIPTION
**Pull request by pires**

### CODE REVIEW

**Comment by pires** [comment]
Care to test it @MaxDaten?

**Comment by tdeheurles** [comment]
Works for me (single node that was broken with 0.21.0).
Didn't seems to have issue on multi-node with 0.21.0

**Comment by MaxDaten** [comment]
Sure, I'm working on it.

**Comment by MaxDaten** [comment]
okay from 1 to 5 instances the cluster seems to be functional. dns is up and running and I started a small http service with a replication controller.

**Comment by pires** [comment]
Thank you all for your feedback.

**Comment by pires** [comment]
@tdeheurles why did you remove your feedback? Thanks nonetheless.

**Comment by tdeheurles** [comment]
I had tested MaxDaten changes, not yours. So it was a bad test return ^^

I work with your changes yesterday, seems to run fine.

**Pull request merged**
