### PR TITLE
fixes pires/kubernetes-vagrant-coreos-cluster#97

### PR DESCRIPTION
**Pull request by MaxDaten**
kubelets working directory is by default `/`
this patch changes the kubelets wd to /root/ where a
.dockercfg file is placed by the Vagrant script

### CODE REVIEW

**Comment by MaxDaten** [comment]
I'm not sure if this fix is valid and if it's a good idea to set the working directory to /root/ for the kubelet. but it should point out the problem for you.

**Comment by AntonioMeireles** [comment]
@MaxDaten when you apply it - does it fix things for you ?

**Comment by MaxDaten** [comment]
it fixes #97 for me. so kubelets can pull private repos when USE_DOCKERCFG is used.

**Comment by AntonioMeireles** [comment]
ok. thnks. good catch!

**Comment by pires** [comment]
Thank you @MaxDaten

**Pull request merged**
