### PR TITLE
Download Kubernetes binaries via synced folders - alternative for wget

### PR DESCRIPTION
**Pull request by ravihansa3000**

### CODE REVIEW

**Comment by pires** [comment]
No changes to cloud-configs?

**Comment by ravihansa3000** [comment]
Actually there are. Sorry, I had overlooked the possibility of only some of the files being copied over via synced folders. Pushed changes to cloud configs as well.

**Comment by pires** [comment]
I'm testing but doesn't seem to work. I run `vagrant up` and binaries are still downloaded for every node.

**Comment by pires** [comment]
@ravihansa3000 any comments?

**Comment by ravihansa3000** [comment]
Agreed. But handling cloud-config changes is going to be bit tricky, hence explicit sync folder approach. I'll see whether it can be improved without too much noise.

**Comment by ravihansa3000** [comment]
@pires care to share your thoughts?

**Comment by pires** [comment]
@ravihansa3000 why not make it available by default?

> source: /opt/kubernetes/v1.2.4/bin

I'd just change this to something like `./binaries`, if relative paths are supported.

**Comment by ravihansa3000** [comment]
@pires Made some changes to make it available by default. Relative paths can be used with File.expand_path. Is this what you are looking for?
One problem is passing mount-options and nfs properties [1]. Parameterizing them would add unnecessary noise. What do you think?

[1] https://github.com/pires/kubernetes-vagrant-coreos-cluster/pull/198/files#diff-23b6f443c01ea2efcb4f36eedfea9089R538

**Comment by pires** [comment]
Let me think about this in the next couple days.

**Comment by pires** [comment]
I am traveling abroad but this is not forgotten. If I don't get back to you in a couple weeks, ping me.

**Comment by pires** [comment]
So @ravihansa3000 a few thoughts:

1. After https://github.com/pires/kubernetes-vagrant-coreos-cluster/pull/194, synced folders are disabled by default. I am open to revert that behavior if it means faster deployments.
2. If synced folders are enabled, the current directory is already available to the VMs thus there's no need to add more stuff.

I'm going to try and make this happen. Will let you know how it goes.

**Comment by pires** [comment]
I just realized your PR depends on manual downloading of the dependencies prior to `vagrant up`. While this works, I'm looking for a seamless way to do so.

Currently, I am downloading the binaries to the host then push to VMs - this has the advantage that synced folders do not need to be re-enabled by default, however can't run Linux binaries on Mac to verify binaries version.

**Comment by pires** [comment]
OK, got the above to work but:
* Before checking if files exist on the host, read a file with the latest version downloaded, e.g. `VERSION`. If file doesn't exist or version read doesn't match the desired version, then download.
* Using `file` provisioner to copy binaries from host to VM is extremely slow (~1.5MB/sec here) so NFS would be the only solution and thus would need to revert #194. @chamilad any comments?

**Comment by pires** [comment]
**FIVE** minutes to copy just the `master` node files!!!
```
==> master: 18:51:57: Copying ./binaries/kube-apiserver to /opt/bin/kube-apiserver..
==> master: 18:52:58: Copied /tmp/kube-apiserver to /opt/bin/kube-apiserver
==> master: 18:52:59: Copying ./binaries/kube-controller-manager to /opt/bin/kube-controller-manager..
==> master: 18:54:07: Copied /tmp/kube-controller-manager to /opt/bin/kube-controller-manager
==> master: 18:54:08: Copying ./binaries/kube-scheduler to /opt/bin/kube-scheduler..
==> master: 18:55:10: Copied /tmp/kube-scheduler to /opt/bin/kube-scheduler
```

**Comment by pires** [comment]
It seems there are no other options and since this repo only supports MacOS X and Linux, I'm going to re-enable NFS and follow that path.

**Comment by ravihansa3000** [comment]
@pires This is all good, but will it work on a Windows machine? Not that it concerns me but I see some commits made to the repo just to make things work on a Windows env.

**Comment by pires** [comment]
@ravihansa3000 while there's Windows support I can't keep with it, since I am not a Windows user. I know NFS should be supported, though.

**Pull request closed without merging**
